spring:
  datasource:
    username: ${USER_NAME}
    password: ${PASSWORD}
    url: jdbc:postgresql://localhost:${POSTGRES_OUT_PORT}/huformation
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: ${SERVER_PORT}